Stop showing deprecation warning
chef-cookbooks/deploy_resource pull request #3
Opened 2018-04-10 09:51 UTC by hagihala

### Description

There is no need to show warning about the depreaction of `deploy` resource when this cookbook is loaded.

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

2018-04-10 14:05 UTC, tas50 requested changes
You can just nuke this method entirely

2018-04-11 03:05 UTC, hagihala commented
I left this method to overwrite the one in the resource bundled with Chef 13.
Otherwise, it will continue to show deprecation warning on Chef 13 run.

2018-04-13 10:10 UTC, thommay approved these changes

2018-05-10 18:14 UTC, tas50 approved these changes

2018-05-10 18:14 UTC, merged